RISTORANTIS/RISTORANTIS/Controllers/PratoDoDiaController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RISTORANTIS.Data;
using RISTORANTIS.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RISTORANTIS.Controllers
{
	public class PratoDoDiaController : Controller
	{
		private readonly RistorantisContext _context;
		private readonly IWebHostEnvironment webHostEnvironment;

		public PratoDoDiaController(RistorantisContext context, IWebHostEnvironment e)
		{
			_context = context;
			webHostEnvironment = e;
		}

		[HttpGet]
		public ActionResult RegistarNovoPrato()
		{
			//só o restaurante consegue aceder a esta página
			if (HttpContext.Session.GetInt32("adminID") != null || HttpContext.Session.GetInt32("ClientID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}
			//Passo 1 para a criação da ViewBag.
			ViewBag.TipoPratoDoDia = new SelectList(_context.TipoPratoDoDia, "IdTipoP", "NomeTipoP");
			return View();
		}

		[HttpPost]
		public ActionResult RegistarNovoPrato(PratoDoDium prato)
		{
			if (ModelState.IsValid)
			{
				//criar um novo prato
				var novo_prato = new PratoDoDium
				{
					Nome = prato.Nome,
					Tipo = prato.Tipo,
				};
				_context.Add(novo_prato);
				_context.SaveChanges();
				HttpContext.Session.SetInt32("pratoID", novo_prato.IdPrato);
				return RedirectToAction("RegistarNovoPrato", "RegistarPD");
			}
			return View(prato);
		}

		
		public ActionResult ApresentarPD()
		{
			//só o restaurante consegue aceder a esta página
			if (HttpContext.Session.GetInt32("adminID") != null || HttpContext.Session.GetInt32("ClientID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}
			//vai buscar os id dos pratos que foram registado pelo restaurante que tiver a sessão iniciada
			var pratosRegistados = _context.Registars.Include(e=>e.IdPratoDoDiaNavigation).Where(r => r.IdPratoDoDia == r.IdPratoDoDiaNavigation.IdPrato && r.IdRestaurante == (int)HttpContext.Session.GetInt32("restID"));
			return View(pratosRegistados.ToList());
		}
				

		//funcao que mostra os detalhes dos pratos do dia
		public ActionResult Detalhes(int? id)
		{
			//só o restaurante consegue aceder a esta página
			if (HttpContext.Session.GetInt32("adminID") != null || HttpContext.Session.GetInt32("ClientID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}

			if (id == null)
			{
				return NotFound();
			}

			var prato = _context.Registars.FirstOrDefault(e => e.IdPratoDoDia == id);
			if (prato == null)
			{
				return NotFound();
			}

			return View(prato);

			

		}

		[HttpGet]
		public ActionResult Apagar(int? id)
        {
			//só o restaurante consegue aceder a esta página
			if (HttpContext.Session.GetInt32("adminID") != null || HttpContext.Session.GetInt32("ClientID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}

			if (id == null)
            {
				return NotFound();
            }
			var prato = _context.PratoDoDia.FirstOrDefault(t=>t.IdPrato == id);

			if(prato == null)
            {
				return NotFound();
            }
			return View(prato);
        }

		[HttpPost, ActionName("Apagar")]
		[ValidateAntiForgeryToken]
		public ActionResult ApagarConfirmacao(int id)
        {
			Registar pratoRegisto = _context.Registars.Where(e => e.IdPratoDoDia == id).Single();
			var pratodoDia = _context.PratoDoDia.Find(id);
			_context.Registars.Remove(pratoRegisto);
			_context.PratoDoDia.Remove(pratodoDia);
			_context.SaveChanges();

			return RedirectToAction("ApresentarPD", "PratoDoDia");
        }
	}
}

RISTORANTIS/RISTORANTIS/Controllers/VisitanteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RISTORANTIS.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RISTORANTIS.Controllers
{
	public class VisitanteController : Controller
	{
		private readonly RistorantisContext _context;
		public VisitanteController(RistorantisContext context)
		{
			_context = context;
		}

		//funçao onde no inicio aparece os restaurantes registados
		public ActionResult PageInicial()
		{
			//condiçoes onde só aparece os utilizadores que sao restaurantes
			var restaurantes = _context.Utilizadors.Include(e => e.Restaurante).Where(e => e.IdUtilizador == e.Restaurante.IdRestaurante && e.Restaurante.EstadoR == "Registado" && e.Estado=="Registado" );
			//var localidades = 
			return View(restaurantes.ToList());
		}

		//funçao onde é listado todos os detalhes de um restaurante
		public ActionResult Detalhes(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var restaurante = _context.Restaurantes.FirstOrDefault(e => e.IdRestaurante == id);
			if (restaurante == null)
			{
				return NotFound();
			}

			return View(restaurante);

		}

		public ActionResult Pesquisa(string searchString)
		{
			var restaurantes = _context.Utilizadors.Include(e => e.Restaurante).Where(e => e.IdUtilizador == e.Restaurante.IdRestaurante && e.Restaurante.EstadoR == "Registado");
			
			if (!String.IsNullOrEmpty(searchString))
			{
				restaurantes = restaurantes.Where(s => s.Nome.Contains(searchString));
			}

			return View("PageInicial", restaurantes.ToList());
			//return RedirectToAction("PageInicial", "Visitante");
		}

		public ActionResult SelecionarFavoritoR()
		{
			return RedirectToAction("Login", "Accounts");
		}

		public ActionResult SelecionarFavoritoP()
		{
			return RedirectToAction("Login", "Accounts");
		}

		public ActionResult PratoDoDia(int? id)
        {
			if (id == null)
			{
				return NotFound();
			}

			//var restaurante = _context.Restaurantes.FirstOrDefault(e => e.IdRestaurante == id);
			var pratosRegistados = _context.Registars.Include(e => e.IdPratoDoDiaNavigation).Where(r => r.IdPratoDoDia == r.IdPratoDoDiaNavigation.IdPrato && r.IdRestaurante == id && r.DataDisponibilidade.Date==DateTime.Today);
			return View(pratosRegistados.ToList());
        }

		public ActionResult Servicos(int? id)
		{
			//mostra os tipos serviços que o restaurante tem:
			var tiposS = _context.SelecionarServicos.Include(s => s.IdRestauranteNavigation).Include(s => s.IdServicoNavigation)
													.Where(s => s.IdRestaurante == id);
			return View(tiposS.ToList());
		}
	}
}

RISTORANTIS/RISTORANTIS/Views/Visitante/Detalhes.cshtml
@model RISTORANTIS.Models.Restaurante

@{
	ViewData["Title"] = "Detalhes";
}

<head>
    <style>
        .button {
            background-color: #F5DEB3;
            border-color: #000000;
            color: #000000;
            padding: 5px 15px;
            text-align: center;
            display: compact;
            font-size: 15px;
        }
    </style>
</head>

<h1>Detalhes</h1>

<link href="~/StyleSheetGeral.css" rel="stylesheet" />

<div>
	<h4>Restaurante</h4>
	<hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>
        <dd class="col-sm-10">
            @{
                var imagem = String.Format("data:image/gif;base64,{0}", Model.Fotografia);
            }
            <img src="@imagem" height="50" width="90" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LocalizacaoGps)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LocalizacaoGps)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EnderecoCodigoPostal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EnderecoCodigoPostal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EnderecoMorada)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EnderecoMorada)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EnderecoLocalidade)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EnderecoLocalidade)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Horario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiaDescanso)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaDescanso)
        </dd>
        <dt hidden class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdRestauranteNavigation)
        </dt>
        <dd hidden class="col-sm-10">
            @Html.DisplayFor(model => model.IdRestauranteNavigation.Email)
        </dd>
    </dl>
</div>
<div>
	<a asp-action="PratoDoDia" asp-route-id="@Model.IdRestaurante" class="btn btn-primary; button">Pratos do Dia</a> <label> |  </label>
	<a asp-action="Servicos" asp-route-id="@Model.IdRestaurante" class="btn btn-primary; button"> Tipos de Serviço </a> <label> |  </label>
	<a asp-action="PageInicial" style="color:black">Voltar ao Início</a> 
</div>

RISTORANTIS/RISTORANTIS/Views/Visitante/PageInicial.cshtml
@model IEnumerable<RISTORANTIS.Models.Utilizador>
@{
    ViewData["Title"] = "PageInicial";
}

<head>
    <style>
        .button {
            background-color: #F5DEB3;
            border-color: #000000;
            color: #000000;
            padding: 5px 15px;
            text-align: center;
            display: compact;
            font-size: 15px;
        }
    </style>
</head>

<link href="~/StyleSheetGeral.css" rel="stylesheet" />

<h1>Restaurantes</h1>
<div class="text-center">
    @*<h1 class="display-4">Bem-Vindo @Context.Session.GetString("user")</h1>*@
    @*<h1 class="display-4">Bem-Vindo </h1>*@
</div>

<form asp-action="Pesquisa" method="get">
    <p>
        <input type="text" name="SearchString" />
        <button style="border:none" type="submit"><img src="~/Icon/download.png" height="15" width="15" /></button>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Restaurante.Fotografia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    
                    @{
                        var imagem = String.Format("data:image/gif;base64,{0}", @item.Restaurante.Fotografia);
                    }

                    <img src="@imagem" height="75" width: auto />
                    @*<img src="@item.Restaurante.Fotografia" height="50" width="100" />*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    <a asp-action="SelecionarFavoritoR">
                        <img id="imagem_fav" height="20" width="20" src="~/Icon/favourite_no.png" />
                    </a>
                </td>
                <td>
                    <a asp-action="Detalhes" asp-route-id="@item.IdUtilizador" style="color:peru" >Detalhes</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RISTORANTIS/RISTORANTIS/Views/Visitante/PratoDoDia.cshtml
@model IEnumerable<RISTORANTIS.Models.Registar>

@{
    ViewData["Title"] = "PratoDoDia";
}

<h1>Prato Do Dia</h1>

<link href="~/StyleSheetGeral.css" rel="stylesheet" />

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fotografia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdPratoDoDiaNavigation.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayName("Tipo de Prato")
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="~/Imagens/@item.Fotografia" height="50" width="90" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdPratoDoDiaNavigation.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @if (item.IdPratoDoDiaNavigation.Tipo == 1)
                {
                    @Html.DisplayName("Carne")
                }
                else if (item.IdPratoDoDiaNavigation.Tipo == 2)
                {
                    @Html.DisplayName("Peixe")
                }
                else if (item.IdPratoDoDiaNavigation.Tipo == 3)
                {
                    @Html.DisplayName("Vegan")
                }
                else if (item.IdPratoDoDiaNavigation.Tipo == 4)
                {
                    @Html.DisplayName("Vegetariano")
                }
            </td>
            @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
            <td>
                <a asp-action="SelecionarFavoritoR">
                    <img id="imagem_fav" height="20" width="20" src="~/Icon/favourite_no.png" />
                </a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="PageInicial" asp-controller="Visitante"> Voltar ao Início </a>
</div>

RISTORANTIS/RISTORANTIS/Views/Visitante/Servicos.cshtml
@model IEnumerable<RISTORANTIS.Models.SelecionarServico>

@{
	ViewData["Title"] = "Servicos";
}

<h1 class="text-center"> Tipos de Serviço do Restaurante</h1>

<link rel="stylesheet" href="~/StyleSheetGeral.css" />

@*<p>
		<a asp-action="Create">Create New</a>
	</p>*@
<table class="table">
	<thead>
		<tr>
			@*<th>
					@Html.DisplayNameFor(model => model.IdRestauranteNavigation)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.IdServicoNavigation)
				</th>*@
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@*@Html.DisplayFor(modelItem => item.IdRestauranteNavigation.DiaDescanso)*@
					@if (item.IdServico == 1)
					{
						@Html.DisplayName("Entrega");
					}
					else if (item.IdServico == 2)
					{
						@Html.DisplayName("Local");
					}
					else if (item.IdServico == 3)
					{
						@Html.DisplayName("Takeway");
					}
				</td>
				@*<td>
						@Html.DisplayFor(modelItem => item.IdServicoNavigation.NomeTipoS)
					</td>*@
				<td>
					@*<a asp-action="Edit" asp-route-id="@item.ID_SelectServico">Edit</a> |
						<a asp-action="Details" asp-route-id="@item.ID_SelectServico">Details</a> |
						<a asp-action="Delete" asp-route-id="@item.ID_SelectServico">Delete</a>*@
				</td>
			</tr>
		}
	</tbody>
</table>

<div>
	<a asp-action="PageInicial" asp-controller="Visitante"> Voltar ao Início </a>
</div>