RISTORANTIS/RISTORANTIS/Models/Bloquear.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace RISTORANTIS.Models
{
    [Table("Bloquear")]
    public partial class Bloquear
    {
        [Key]
        [Column("Data_Bloquear", TypeName = "date")]
        public DateTime DataBloquear { get; set; }
        [Required]
        [Column("Motivo_Bloqueio")]
        [StringLength(100)]
        public string MotivoBloqueio { get; set; }
        [Column("Data_Desbloqueio", TypeName = "date")]
        public DateTime? DataDesbloqueio { get; set; }
        [Key]
        [Column("ID_Administrador")]
        public int IdAdministrador { get; set; }
        [Key]
        [Column("ID_Utilizador")]
        public int IdUtilizador { get; set; }

        [ForeignKey(nameof(IdAdministrador))]
        [InverseProperty(nameof(Administrador.Bloquears))]
        public virtual Administrador IdAdministradorNavigation { get; set; }
        [ForeignKey(nameof(IdUtilizador))]
        [InverseProperty(nameof(Utilizador.Bloquears))]
        public virtual Utilizador IdUtilizadorNavigation { get; set; }
    }
}

RISTORANTIS/RISTORANTIS/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace RISTORANTIS.Models
{
    [Table("Cliente")]
    public partial class Cliente
    {
        public Cliente()
        {
            SelecionarPFavoritos = new HashSet<SelecionarPFavorito>();
            SelecionarRFavoritos = new HashSet<SelecionarRFavorito>();
        }

        [Key]
        [Column("ID_Cliente")]
        public int IdCliente { get; set; }

        [ForeignKey(nameof(IdCliente))]
        [InverseProperty(nameof(Utilizador.Cliente))]
        public virtual Utilizador IdClienteNavigation { get; set; }
        [InverseProperty(nameof(SelecionarPFavorito.IdClienteNavigation))]
        public virtual ICollection<SelecionarPFavorito> SelecionarPFavoritos { get; set; }
        [InverseProperty(nameof(SelecionarRFavorito.IdClienteNavigation))]
        public virtual ICollection<SelecionarRFavorito> SelecionarRFavoritos { get; set; }
    }
}

RISTORANTIS/RISTORANTIS/Controllers/AdministradoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RISTORANTIS.Data;
using RISTORANTIS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RISTORANTIS.Controllers
{
	public class AdministradoresController : Controller
	{
		private readonly RistorantisContext _context;
		public AdministradoresController(RistorantisContext context)
		{
			_context = context;
		}

		//função que apresenta o Menu Inicial
		public ActionResult Painel()
		{
			//só o admin consegue aceder ao seu proprio menu
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}
			if(HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}
			return View();
		}

		//funçáo que mostra os administradores criados pelo próprio administradores
		public ActionResult VerAdministradores()
		{
			//só o admin consegue aceder a esta página
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}

			var administradores = _context.Administradors.Where(a => a.IdCriador == (int)HttpContext.Session.GetInt32("adminID"));
			return View(administradores.ToList());
		}
		

		//funçáo que mostra a lista de clientes
		public ActionResult Clientes()
		{

			//só o admin consegue aceder a esta página
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}
			var clientes = _context.Utilizadors.Include(p =>p.Cliente).Where(p => p.Cliente.IdCliente == p.IdUtilizador);
			return View(clientes.ToList());
		}

		//função para registar um Administrador
		public ActionResult RegistarAdministrador(int id)
		{
			//procura na BD pelo utilizador com o id que foi recebido como parametro
			Utilizador user = _context.Utilizadors.Where(u => u.IdUtilizador == id).Single();
			//verifca se já não é um administrador (por precaução!!)
			var admin = _context.Administradors.Where(p => p.Email == user.Email && p.Username == user.Username).Any();
			

			if (admin == false && user != null)
			{
				//adiciona um novo administradores aproveitando os seu dados anteriores que tinha de utilizador
				var novo_admnistrador = new Administrador()
				{
					Username = user.Username,
					Nome = user.Nome,
					Email = user.Email,
					Password = user.Password,
					IdCriador =(int)HttpContext.Session.GetInt32("adminID") // id do admnistrador que o criou
				};
				_context.Administradors.Add(novo_admnistrador);

				//remove o utilizador da BD de utilizadores
				ApagarUtilizador(id);
				_context.SaveChanges();
				return RedirectToAction("VerAdministradores");

			}
			else
			{
				return View("Clientes");
			}


			return View();
		}


		//função para apagar Utilizador da BD
		public void  ApagarUtilizador(int id)
		{
			//Procura o utilizador na BD
			var utilizador = _context.Utilizadors.Find(id);
			var cliente = _context.Clientes.Find(id);
			if (utilizador != null && cliente != null)
			{
				//Apaga a linha na BD
				_context.Clientes.Remove(cliente);
				_context.Utilizadors.RemoveRange(utilizador);
				_context.SaveChanges();
				
			}
	
		}

		//função para mostrar os pedidos dos restaurantes
		public ActionResult PedidosRestaurante()
		{
			//só o admin consegue aceder a esta página
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}
			//vai buscar os dados de pedidos que ainda não foram aceites!
			var pedidos = _context.PedirRegistos.Include(e => e.IdRestauranteNavigation.IdRestauranteNavigation).Include(e => e.IdRestauranteNavigation.IdRestauranteNavigation.Restaurante)
													.Where(e=>e.IdAdministrador == null);
			return View(pedidos.ToList());
		}

		//função para aceitar pedidos
		[HttpGet]
		public ActionResult AceitarPedidos(int? id)
		{
			//só o admin consegue aceder a esta página
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}

			if (id == null)
			{
				return NotFound();
			}
			var pedido = _context.PedirRegistos.Find(id);
			if(pedido == null)
			{
				return NotFound();
			}

			return View(pedido);
		}
		
		[HttpPost]
		public ActionResult AceitarPedidos(PedirRegisto pedido ,int id)
		{
			if(HttpContext.Session.GetInt32("adminID") == null)
			{
				return NotFound();
			}
			else
			{
				pedido.IdPedirRegisto = id;

				//retorna o id do restaurante que está a fazer o pedido
				var restaurantes = _context.PedirRegistos.Include(e=>e.IdRestauranteNavigation)
										.Where(r => r.IdRestaurante == r.IdRestauranteNavigation.IdRestaurante && r.IdPedirRegisto == id).Select(r => r.IdRestauranteNavigation.IdRestaurante).First();
				pedido.IdRestaurante = restaurantes;

				if(ModelState.IsValid)
				{
					//atauliza os valores da tabela Pedir Registos necessários
					_context.PedirRegistos.Where(r => r.IdPedirRegisto == id).First().IdAdministrador = (int)HttpContext.Session.GetInt32("adminID");
					_context.PedirRegistos.Where(r => r.IdPedirRegisto == id).First().Resultado = pedido.Resultado;
					_context.PedirRegistos.Where(r => r.IdPedirRegisto == id).First().DataAceitacao = DateTime.Now;
					//atualiza o estado da tabela restaurantes para depois o restaurante se puder registar
					_context.Restaurantes.Where(r => r.IdRestaurante == pedido.IdRestaurante).First().EstadoR = "Registado";
					_context.SaveChanges();

					return RedirectToAction("PedidosRestaurante");
				}
			}

			return RedirectToAction("PedidosRestaurante");
		}

		//função qpara rejitar o pedido
		[HttpGet]
		public ActionResult RejeitarPedidos(int? id)
		{
			//só o admin consegue aceder a esta página
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}

			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}

			if (id == null)
			{
				return NotFound();
			}
			var pedido = _context.PedirRegistos.Find(id);
			if (pedido == null)
			{
				return NotFound();
			}

			return View(pedido);
		}

		[HttpPost]
		public ActionResult RejeitarPedidos(PedirRegisto pedido, int id)
		{
			if (HttpContext.Session.GetInt32("adminID") == null)
			{
				return NotFound();
			}
			else
			{
				pedido.IdRestaurante = id;

				var restaurantes = _context.PedirRegistos.Include(e => e.IdRestauranteNavigation)
										.Where(r => r.IdRestaurante == r.IdRestauranteNavigation.IdRestaurante).Select(r => r.IdRestauranteNavigation.IdRestaurante).First();
				pedido.IdRestaurante = restaurantes;


				if (ModelState.IsValid)
				{
					if(pedido.MotivoRejeicao == null)
					{
						ModelState.AddModelError("", "O campo Motivo de Rejeição é de preenchimento obrigatório!");
						return View("RejeitarPedidos");
					}
					//atauliza os valores da tabela Pedir Registos necessários
					_context.PedirRegistos.Where(r => r.IdPedirRegisto == id).First().IdAdministrador = (int)HttpContext.Session.GetInt32("adminID");
					_context.PedirRegistos.Where(r => r.IdPedirRegisto == id).First().Resultado = pedido.Resultado;
					_context.PedirRegistos.Where(r => r.IdPedirRegisto == id).First().MotivoRejeicao = pedido.MotivoRejeicao;
					//atualiza o estado da tabela restaurantes para depois o restaurante se puder registar
					_context.Restaurantes.Where(r => r.IdRestaurante == pedido.IdRestaurante).First().EstadoR = "Rejeitado";
					_context.SaveChanges();

					return RedirectToAction("PedidosRestaurante");
				}
			}

			return RedirectToAction("PedidosRestaurante");

			return View();
		}


		//função para alterar dados do utilizador
		[HttpGet]
		public ActionResult AlterarDadosA()
		{
			//só o admin consegue aceder a esta página
			if (HttpContext.Session.GetInt32("ClientID") != null || HttpContext.Session.GetInt32("restID") != null)
			{
				return View("Error403");
			}
			if (HttpContext.Session.GetInt32("ClientID") == null && HttpContext.Session.GetInt32("restID") == null && HttpContext.Session.GetInt32("adminID") == null)  // o visitante não pode ter acesso a esta pagina
			{
				return View("Error403");
			}

			if (HttpContext.Session.GetInt32("adminID") == null)
			{
				return NotFound();
			}

			//vai procurar na BD pelos dados do id do utilizador
			var admin = _context.Administradors.Find(HttpContext.Session.GetInt32("adminID"));
			if (admin == null)
			{
				return NotFound();
			}

RISTORANTIS/RISTORANTIS/Views/Administradores/Detalhes.cshtml
@model RISTORANTIS.Models.Restaurante

@{
    ViewData["Title"] = "Detalhes";
}

<head>
    <style>
        .button {
            background-color: #F5DEB3;
            border-color: #000000;
            color: #000000;
            padding: 5px 20px;
            text-align: center;
            display: compact;
            font-size: 15px;
        }
    </style>
</head>

<h1 class="text-center">Detalhes Do Restaurante</h1>

<link rel="stylesheet" href="~/StyleSheetGeral.css"/>

<div>
    @*<h4>Restaurante</h4>*@
    <hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Telefone)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Telefone)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.LocalizacaoGps)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.LocalizacaoGps)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.EnderecoCodigoPostal)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.EnderecoCodigoPostal)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.EnderecoMorada)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.EnderecoMorada)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.EnderecoLocalidade)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.EnderecoLocalidade)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Horario)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Horario)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.DiaDescanso)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.DiaDescanso)
		</dd>
		<dt class="col-sm-2" hidden>
			@Html.DisplayNameFor(model => model.EstadoR)
		</dt>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Fotografia)
		</dt>
		<dd class="col-sm-10">
			@*@Html.DisplayFor(model => model.Fotografia)*@
			@*<img src="~/Imagens/@Model.Fotografia" height="50" width="100" />*@

			@{
				var imagem = String.Format("data:image/gif;base64,{0}", Model.Fotografia);
			}
			<img src="@imagem" height="75" width: auto />
		</dd>
		<div>
			@if (Model.EstadoR == "Registado")
			{
				<a asp-action="DetalhesPR" asp-route-id="@Model.IdRestaurante" class="btn btn-primary; button" > Pratos do Dia </a> 
				<a asp-action="Servicos" asp-controller="Administradores" asp-route-id="@Model.IdRestaurante" class="btn btn-primary; button" > Tipos de Serviço </a> 
				<a asp-action="GerirUtilizadores" asp-controller="Administradores" style="color:black"> Voltar </a>
			}
			else
			{
				<a asp-action="Servicos" asp-controller="Administradores" asp-route-id="@Model.IdRestaurante" class="btn btn-primary; button"> Tipos de Serviço </a> 
				<a asp-action="PedidosRestaurante" asp-controller="Administradores" style="color:black"> Voltar </a>

			}
		</div>
	</dl>
</div>

RISTORANTIS/RISTORANTIS/Views/Administradores/DetalhesPR.cshtml
@model IEnumerable<RISTORANTIS.Models.Registar>

@{
    ViewData["Title"] = "DetalhesPR";
}

<h1 class="text-center"> Lista de Pratos Registados </h1>

<link rel="stylesheet" href="~/StyleSheetGeral.css" />

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Fotografia)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.IdPratoDoDiaNavigation.Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.IdPratoDoDiaNavigation.Tipo)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Descricao)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Preco)
			</th>
		</tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
			<td>
				<img src="~/Imagens/@item.Fotografia" height="100" width="150" />
			</td>
            <td>
                @Html.DisplayFor(modelItem => item.IdPratoDoDiaNavigation.Nome)
            </td>
			<td>
				@if (item.IdPratoDoDiaNavigation.Tipo == 1)
				{
					@Html.DisplayName("Carne")
				}
				else if (item.IdPratoDoDiaNavigation.Tipo == 2)
				{
					@Html.DisplayName("Peixe")
				}
				else if (item.IdPratoDoDiaNavigation.Tipo == 3)
				{
					@Html.DisplayName("Vegan")
				}
				else if (item.IdPratoDoDiaNavigation.Tipo == 4)
				{
					@Html.DisplayName("Vegetariano")
				}

				@*@Html.DisplayFor(modelItem => item.IdPratoDoDiaNavigation.TipoNavigation.NomeTipoP)*@

			</td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
        </tr>
	}
    </tbody>
</table>

<div>
	<a asp-action="GerirUtilizadores" asp-controller="Administradores" style="color:black"> Voltar </a>
</div>

RISTORANTIS/RISTORANTIS/Views/Administradores/GerirUtilizadores.cshtml
@model IEnumerable<RISTORANTIS.Models.Utilizador>

@{
    ViewData["Title"] = "GerirUtilizadores";
}

<h1 class="text-center">Gerir Utilizadores</h1>

<div class="text-center">
    @Html.ActionLink("Restaurantes", "ProcurarRestaurantes", "Administradores", null, new { style = "background-color:wheat; border-color:black; color:black; height:40px; width:200px", @class = "btn btn-primary; text-center" })
    @Html.ActionLink("Clientes", "ProcurarClientes", "Administradores", null, new { style = "background-color:wheat; border-color:black; color:black; height:40px; width:200px", @class = "btn btn-primary" })
    @Html.ActionLink("Utilizadores", "GerirUtilizadores", "Administradores", null, new { style = "background-color:wheat; border-color:black; color:black; height:40px; width:200px", @class = "btn btn-primary" })
</div>
<br />

<link href="~/StyleSheetGeral.css" rel="stylesheet" />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
      
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
				<td>
					@if (item.Estado == "Bloqueado")
					{
						<a asp-action="Desbloquear" asp-route-id="@item.IdUtilizador" style="color:peru">Desbloquear</a> <label> | </label>
						@*<a asp-action="Detalhes"  asp-controller="Administradores"  asp-route-id="@item.IdUtilizador" style="color:peru"> Detalhes </a>*@
					}
					@if (item.Cliente != null && item.Restaurante == null)
					{
						<a asp-action="Bloquear" asp-route-id="@item.IdUtilizador" style="color:peru">Bloquear</a> 
						@*<a asp-action="Detalhes" asp-controller="Administradores" asp-route-id="@item.IdUtilizador" style="color:peru">Detalhes</a>*@
					}
					else if (item.Restaurante != null && item.Cliente == null)
					{
						<a asp-action="Bloquear" asp-route-id="@item.IdUtilizador" style="color:peru">Bloquear</a> <label> | </label>
						<a asp-action="Detalhes" asp-controller="Administradores" asp-route-id="@item.IdUtilizador" style="color:peru">Detalhes</a>
					}
				</td>
            </tr>
        }

    </tbody>
</table>

<div>
    <a asp-action="Painel" style="color:black">Voltar ao Menu</a>
</div>

RISTORANTIS/RISTORANTIS/Views/Administradores/Painel.cshtml
@{ ViewData["Title"] = "Painel"; }


@*<div class="text-center">
        <h1 class="display-4">Bem-Vindo @Context.Session.GetString("admin")</h1>
    </div>*@
<div class="text-center">
    <h1 class="display-4">Bem-Vindo @Context.Session.GetString("nome")</h1>
</div>

<link href="~/StyleSheetGeral.css" rel="stylesheet" />

<h1 class="text-center">Menu de Administrador</h1>
@*<h1>Menu Principal</h1>*@
<form asp-action="Painel">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

	<div class="text-center">
		<br />
		@Html.ActionLink("Pedidos de Restaurante", "PedidosRestaurante", "Administradores", null, new { style = "background-color:wheat; border-color:black; color: black; height: 40px; width: 240px", @class = "btn btn-primary" })
		<br />
		<br />
		@Html.ActionLink("Gerir Utilizadores", "GerirUtilizadores", "Administradores", null, new { style = "background-color:wheat; border-color:black; color: black; height: 40px; width: 240px", @class = "btn btn-primary" })
		<br />
		<br />
		@Html.ActionLink("Alterar Dados", "AlterarDadosA", "Administradores", null, new { style = "background-color:wheat; border-color:black; color: black; height: 40px; width: 240px", @class = "btn btn-primary" })
		<br />
		<br />
		@Html.ActionLink("Adicionar Adminstradores", "VerAdministradores", "Administradores", null, new { style = "background-color:wheat; border-color:black; color: black; height: 40px; width: 240px", @class = "btn btn-primary" })
	</div>

</form>

RISTORANTIS/RISTORANTIS/Views/Administradores/PedidosRestaurante.cshtml
@model IEnumerable<RISTORANTIS.Models.PedirRegisto>

@{
    ViewData["Title"] = "Pedidos de Restaurante";
}

<h1>Pedidos de Restaurante</h1>

<link href="~/StyleSheetGeral.css" rel="stylesheet" />

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdRestauranteNavigation.Fotografia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdRestauranteNavigation.IdRestauranteNavigation.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdRestauranteNavigation.IdRestauranteNavigation.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdRestauranteNavigation.IdRestauranteNavigation.Username)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @*@Html.DisplayFor(modelItem => item.IdRestauranteNavigation.)*@

                @{
                    var imagem = String.Format("data:image/gif;base64,{0}", item.IdRestauranteNavigation.Fotografia);
                }
                <img src="@imagem" height="75" width: auto />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdRestauranteNavigation.IdRestauranteNavigation.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdRestauranteNavigation.IdRestauranteNavigation.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdRestauranteNavigation.IdRestauranteNavigation.Username)
            </td>
            <td>
                <a asp-action="AceitarPedidos" asp-route-id="@item.IdPedirRegisto" style="color:peru"> Aceitar </a> |
                <a asp-action="RejeitarPedidos" asp-route-id="@item.IdPedirRegisto" style="color:peru"> Rejeitar </a> |
                <a asp-action="Detalhes" asp-controller="Administradores" asp-route-id="@item.IdRestaurante" style="color:peru"> Detalhes </a>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Painel" style="color:black">Voltar ao Menu</a>
</div>

RISTORANTIS/RISTORANTIS/Views/Administradores/Servicos.cshtml
@model IEnumerable<RISTORANTIS.Models.SelecionarServico>

@{
    ViewData["Title"] = "Servicos";
}

<h1 class="text-center"> Tipos de Serviço do Restaurante</h1>

<link rel="stylesheet" href="~/StyleSheetGeral.css"/>
@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.IdServicoNavigation.IdServico)
            </th>*@
            @*<th>
                @Html.DisplayNameFor(model => model.IdServicoNavigation)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
			<td>
				@if (item.IdServico == 1)
				{
					@Html.DisplayName("Entrega");
				}
				else if (item.IdServico == 2)
				{
					@Html.DisplayName("Local");
				}
				else if (item.IdServico == 3)
				{
					@Html.DisplayName("Takeway");
				}
			</td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IdServicoNavigation.NomeTipoS)
            </td>*@
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.ID_SelectServico">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID_SelectServico">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID_SelectServico">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Painel" asp-controller="Administradores" style="color:black"> Voltar ao Menu </a>
</div>